the_transcript = [
(13, "North America was named Jamestown in"),
(16, "Virginia it was 1607 and the migration"),
(19, "and colonization of Great Britain"),
(21, "continued by the 1770s thirteen colonies"),
(25, "had admired the colonists in America"),
(28, "were citizens of Great Britain and"),
(30, "subject to King George the third who"),
(33, "appointed royal governors throughout the"),
(35, "colonies the colonies were the property"),
(38, "of Great Britain with whom they were"),
(41, "required to trade and to whom the"),
(43, "colonists required to pay taxes"),
(46, "increasing control from England was met"),
(49, "with resistance for example Parliament"),
(52, "passed the quartering act which stated"),
(55, "that the Americans needed to either pay"),
(58, "for or provide lodging and support for"),
(64, "the colonists thought this was crazy"),
(66, "another harsh tax came through the Stamp"),
(69, "Act which required that many printed"),
(71, "materials in the colonies be produced on"),
(74, "specially stamped paper produced in"),
(77, "London these materials included legal"),
(81, "papers magazines newspapers and playing"),
(84, "cards"),
(85, "the Americans began to push back they"),
(89, "refused to buy British goods and trade"),
(91, "with Great Britain the bottom line is"),
(93, "that the decision and taxes were being"),
(96, "imposed upon these American colonists"),
(98, "and they had no vote no control no"),
(102, "influence and no representation in the"),
(105, "Parliament of England complaints to the"),
(108, "King were ignored in Boston"),
(111, "Massachusetts some colonists protested"),
(113, "by disguising themselves as Indians"),
(115, "sneaking aboard ships in the harbor they"),
(118, "dumped the cargo of tea into the sea"),
(123, "britain to close the port and impose"),
(125, "punishment for this rebellion the other"),
(127, "colonies also rebelled which began the"),
(130, "outbreak of the American Revolutionary"),
(132, "War"),
(133, "in 1775 the Second Continental Congress"),
(137, "was organized by delegates and"),
(139, "representatives of the American colonies"),
(142, "these men gathered to decide what would"),
(145, "and could be done to defend the rights"),
(147, "and lives of the Americans against the"),
(150, "tyranny of Great Britain the")
]

print("the_transcript:",the_transcript)

example_ideas = [(13, 'North America was named Jamestown in Virginia; it was 1607 and the migration and colonization of Great Britain continued by the 1770s'), (19, 'Thirteen colonies had admired the colonists in America; they were citizens of Great Britain and subject to King George the third, who appointed royal governors throughout the colonies'), (25, 'The colonies were the property of Great Britain with whom they were required to trade and to whom the colonists required to pay taxes'), (30, 'Increasing control from England was met with resistance; for example, Parliament passed the quartering act which stated that the Americans needed to either pay for or provide lodging and support for the colonists'), (33, 'This was thought to be crazy; another harsh tax came through the Stamp Act, which required that many printed materials in the colonies be produced on specially stamped paper produced in London'), (38, 'These materials included legal papers, magazines, newspapers, and playing cards'), (41, 'The Americans began to push back; they refused to buy British goAmerican colonists and they had no vote, no control, no influence, and no representation in the Parliament of England'), (46, 'Complaints to the King were ignored; in Boston, Massachusetts, some colonists protested by disguising themselves as Indians'), (50, 'They snuck aboard ships in the harbor and dumped the cargo of tea into the sea; in response, Britain closed the port and imposed punishment for this rebellion'), (55, 'The other colonies also rebelled, which began the outbreak of the American Revolutionary War'), (58, 'In 1775, the Second Continental Congress was organized by delegates and representatives of the American colonies'), (63, 'These men gathered to decide what would and could be done to defend the rights and lives of the Americans against the tyranny of Great Britain')]